<?xml version="1.0" encoding="UTF-8"?><testrun name="TestCalculator" project="StringCalculator" tests="8" started="8" failures="0" errors="1" ignored="0">
  <testsuite name="stringCalculator.TestCalculator" time="0.003">
    <testcase name="emptyStringReturn0" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="addUnknownAmountOfNumber" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="numberOfLengthOne" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="ignoreNumberGreaterThan1000" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="customDeliminator" classname="stringCalculator.TestCalculator" time="0.002">
      <error>java.lang.IllegalStateException: No match found&#13;
	at java.util.regex.Matcher.group(Unknown Source)&#13;
	at stringCalculator.Calculator.customDeliminater(Calculator.java:69)&#13;
	at stringCalculator.Calculator.tokenize(Calculator.java:58)&#13;
	at stringCalculator.Calculator.add(Calculator.java:18)&#13;
	at stringCalculator.TestCalculator.customDeliminator(TestCalculator.java:41)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
&#13;
</error>
    </testcase>
    <testcase name="handleNewLinebetweenNumber" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="negativeNumberException" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="sumOfNumberSeperatedByComma" classname="stringCalculator.TestCalculator" time="0.001"/>
  </testsuite>
</testrun>
