<?xml version="1.0" encoding="UTF-8"?><testrun name="TestCalculator" project="StringCalculator" tests="7" started="7" failures="1" errors="0" ignored="0">
  <testsuite name="stringCalculator.TestCalculator" time="0.004">
    <testcase name="emptyStringReturn0" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="addUnknownAmountOfNumber" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="numberOfLengthOne" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="customDeliminator" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="handleNewLinebetweenNumber" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="negativeNumberException" classname="stringCalculator.TestCalculator" time="0.002">
      <failure>
        <expected>Negative number not allowed:</expected>
        <actual>Negative number not allowed:[-1]</actual>org.junit.ComparisonFailure: expected:&lt;... number not allowed:[]&gt; but was:&lt;... number not allowed:[[-1]]&gt;&#13;
	at org.junit.Assert.assertEquals(Assert.java:115)&#13;
	at org.junit.Assert.assertEquals(Assert.java:144)&#13;
	at stringCalculator.TestCalculator.negativeNumberException(TestCalculator.java:54)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="sumOfNumberSeperatedByComma" classname="stringCalculator.TestCalculator" time="0.002"/>
  </testsuite>
</testrun>
